### PR TITLE
Reusuable header

### PR DESCRIPTION
**Pull request by CSCairney-GL**

### CODE REVIEW

**Review by CSCairney-GL — COMMENTED** [review]
Altered existing carousel component to allow single image headers, that removes all pagination and mobile mechanics.

**Review by jab-khanGL — APPROVED** [review]
Looks good to me

**Review by MihneaDinuGL — COMMENTED** [review]
Looks great! Just wondering, why did you go from having CarouselCards and SlideDots as their own components to having them be part of the MainCarousel component? Was there an issue with passing the props?

**Comment by CSCairney-GL** [comment]
> Looks great! Just wondering, why did you go from having CarouselCards and SlideDots as their own components to having them be part of the MainCarousel component? Was there an issue with passing the props?

@MihneaDinuGL Thanks Alex and no issues passing the props but had a discussion with Jab and it seemed unnecessary to have them external to the main carousel when they're core functions that only the main uses and their CSS is built in quite a specific way that they would require alot of change to retrofit into something else so just brought them back in :)

**Comment by MihneaDinuGL** [comment]
> 

Oh I see, great stuff :)

**Review by MihneaDinuGL — APPROVED** [review]

**Review by sourcesmith — APPROVED** [review]

**Pull request merged**
